import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "24px",
        md: "40px",
        lg: "64px",
      },
      screens: {
        "2xl": "1440px",
      },
    },
    extend: {
      colors: {
        white: "var(--color-white)",
        "text-strong": "var(--color-text-primary)",
        "text-body": "var(--color-text-body)",
        "text-muted": "var(--color-text-muted)",
        "text-disabled": "var(--color-text-disabled)",
        "brand-primary": "var(--color-primary)",
        "brand-primary-ios": "var(--color-primary-ios)",

        background: "var(--background)",
        surface: "var(--surface)",
        "surface-bright": "var(--surface-bright)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-variant": "var(--surface-variant)",

        "on-background": "var(--on-background)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "inverse-surface": "var(--inverse-surface)",

        primary: "var(--primary)",
        "on-primary": "var(--on-primary)",
        "primary-container": "var(--primary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed": "var(--primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-tint": "var(--surface-tint)",

        secondary: "var(--secondary)",
        "on-secondary": "var(--on-secondary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",

        tertiary: "var(--tertiary)",
        "on-tertiary": "var(--on-tertiary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",

        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",

        // Canonical card-surface borders. Use these (not outline-variant)
        // for any rounded card/panel/tile across the app. See
        // `.cursor/rules/card-borders.mdc` for full guidance.
        "card-border": "var(--border-card)",
        "card-border-hover": "var(--border-card-hover)",
        "card-divider": "var(--border-card-divider)",
        "card-divider-hover": "var(--border-card-divider-hover)",

        error: "var(--error)",
        "on-error": "var(--on-error)",
        "error-container": "var(--error-container)",
        "on-error-container": "var(--on-error-container)",
      },
      fontFamily: {
        // `serif`/`font-serif` is a legacy token: same Manrope stack as sans.
        serif: [
          "var(--font-serif)",
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        sans: [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        primary: [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        system: [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        "display-lg": [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        "headline-lg": [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        "headline-md": [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        "body-lg": [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        "body-md": [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        "label-caps": [
          "var(--font-sans)",
          "Manrope",
          "var(--font-ethiopic)",
          "Noto Sans Ethiopic",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "700" },
        ],
        spec: ["var(--font-size-base)", { lineHeight: "var(--line-height-base)" }],
        "spec-sm": [
          "var(--font-size-small)",
          { lineHeight: "var(--line-height-base)" },
        ],
      },
      borderRadius: {
        DEFAULT: "var(--radius-default)",
        none: "0",
        sm: "var(--radius-default)",
        md: "var(--radius-lg)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-xl)",
        "3xl": "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      spacing: {
        unit: "var(--space-unit)",
        gutter: "var(--space-gutter)",
        "margin-edge": "var(--space-margin-edge)",
        edge: "var(--space-margin-edge)",
        "section-gap": "var(--space-section-gap)",
        section: "var(--space-section-gap)",
        "container-max": "var(--container-max)",
      },
      maxWidth: {
        /** Full-bleed page chrome (matches sticky header insets); no 1440px cap. */
        container: "none",
        "container-max": "none",
        prose: "68ch",
      },
      boxShadow: {
        editorial: "var(--editorial-shadow)",
        none: "none",
      },
      backdropBlur: {
        glass: "var(--glass-blur)",
      },
      transitionTimingFunction: {
        editorial: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "fade-in": "fade-in 600ms var(--ease-out, cubic-bezier(0.22, 1, 0.36, 1)) both",
        "fade-up": "fade-up 700ms var(--ease-out, cubic-bezier(0.22, 1, 0.36, 1)) both",
        shimmer: "shimmer 2.2s linear infinite",
        marquee: "marquee 40s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
